version: "3.8"

services:
  redis: &main_app
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    volumes:
      - .:/app
    command: python run_redis.py
    networks:
      - app-network

  celery:
    <<: *main_app
    volumes:
      - .:/app
    command: celery -A run_api.celery worker --loglevel=info --pool=solo
    networks:
      - app-network

  web:
    <<: *main_app
    command: uvicorn run_api:app --reload
    ports:
      - "8000:8000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
