version: '3.9'

services:
  api: &main_app
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
      target: prod
    image: bert4rec_service:${BERT4REC_SERVICE_VERSION:-latest}
    restart: always
    env_file:
    - .env
    labels:
      # Enables traefik for this container.
    - traefik.enable=true
    - traefik.http.routers.bert4rec_service.rule=Host(`${BERT4REC_SERVICE_TRAEFIK_HOST:-bert4rec_service.localhost}`)
    - traefik.http.routers.bert4rec_service.entrypoints=http
    - traefik.http.routers.bert4rec_service.service=bert4rec_service
    - traefik.http.services.bert4rec_service.loadbalancer.server.port=${BERT4REC_SERVICE_PORT:-8000}
    networks:
    - default
    - traefik-shared
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      BERT4REC_SERVICE_HOST: 0.0.0.0
      BERT4REC_SERVICE_DB_HOST: bert4rec_service-db
      BERT4REC_SERVICE_DB_PORT: 5432
      BERT4REC_SERVICE_DB_USER: bert4rec_service
      BERT4REC_SERVICE_DB_PASS: bert4rec_service
      BERT4REC_SERVICE_DB_BASE: bert4rec_service
      BERT4REC_SERVICE_REDIS_HOST: bert4rec_service-redis
      TESTKAFKA_KAFKA_BOOTSTRAP_SERVERS: '["bert4rec_service-kafka:9092"]'

  taskiq-worker:
    <<: *main_app
    labels: []
    command:
    - taskiq
    - worker
    - bert4rec_service.tkq:broker

  db:
    image: postgres:13.8-bullseye
    hostname: bert4rec_service-db
    environment:
      POSTGRES_PASSWORD: "bert4rec_service"
      POSTGRES_USER: "bert4rec_service"
      POSTGRES_DB: "bert4rec_service"
    volumes:
    - bert4rec_service-db-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: pg_isready -U bert4rec_service
      interval: 2s
      timeout: 3s
      retries: 40

  migrator:
    image: bert4rec_service:${BERT4REC_SERVICE_VERSION:-latest}
    restart: "no"
    command: alembic upgrade head
    environment:
      BERT4REC_SERVICE_DB_HOST: bert4rec_service-db
      BERT4REC_SERVICE_DB_PORT: 5432
      BERT4REC_SERVICE_DB_USER: bert4rec_service
      BERT4REC_SERVICE_DB_PASS: bert4rec_service
      BERT4REC_SERVICE_DB_BASE: bert4rec_service
    depends_on:
      db:
        condition: service_healthy

  redis:
    image: bitnami/redis:6.2.5
    hostname: "bert4rec_service-redis"
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 50

  zookeeper:
    image: "bitnami/zookeeper:3.7.1"
    hostname: "bert4rec_service-zookeeper"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
      ZOO_LOG_LEVEL: "ERROR"
    healthcheck:
      test: zkServer.sh status
      interval: 1s
      timeout: 3s
      retries: 30

  kafka:
    image: "bitnami/kafka:3.2.0"
    hostname: "bert4rec_service-kafka"
    environment:
      KAFKA_BROKER_ID: "1"
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://0.0.0.0:9092"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://bert4rec_service-kafka:9092"
      KAFKA_CFG_ZOOKEEPER_CONNECT: "bert4rec_service-zookeeper:2181"
    healthcheck:
      test: kafka-topics.sh --list --bootstrap-server localhost:9092
      interval: 1s
      timeout: 3s
      retries: 30
    depends_on:
      zookeeper:
        condition: service_healthy



volumes:
  bert4rec_service-db-data:
    name: bert4rec_service-db-data

networks:
  # Network for traefik.
  traefik-shared:
    name: traefik-shared
