version: "3.8"

services:
  redis: &main_app
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    volumes:
      - .:/app
    command: python run_redis.py
    ports:
      - "6379:6379"

  celery:
    <<: *main_app
    volumes:
      - .:/app
    command: celery -A run_api.celery worker --loglevel=info --pool=solo
    ports:
      - "8001:8001"
    depends_on:
      - redis

  web:
    <<: *main_app
    command: uvicorn run_api:app --reload
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - celery
